//! PS/2 Set 1 scan codes, and the map from the neutral [`Key`] onto them.

use alluno_input_core::Key;

/// The Set 1 make codes the filter driver takes.
pub mod code {
    pub const ESC: u16 = 0x01;
    pub const NUM1: u16 = 0x02;
    pub const NUM2: u16 = 0x03;
    pub const NUM3: u16 = 0x04;
    pub const NUM4: u16 = 0x05;
    pub const NUM5: u16 = 0x06;
    pub const NUM6: u16 = 0x07;
    pub const NUM7: u16 = 0x08;
    pub const NUM8: u16 = 0x09;
    pub const NUM9: u16 = 0x0A;
    pub const NUM0: u16 = 0x0B;
    pub const MINUS: u16 = 0x0C;
    pub const EQUALS: u16 = 0x0D;
    pub const BACKSPACE: u16 = 0x0E;
    pub const TAB: u16 = 0x0F;
    pub const Q: u16 = 0x10;
    pub const W: u16 = 0x11;
    pub const E: u16 = 0x12;
    pub const R: u16 = 0x13;
    pub const T: u16 = 0x14;
    pub const Y: u16 = 0x15;
    pub const U: u16 = 0x16;
    pub const I: u16 = 0x17;
    pub const O: u16 = 0x18;
    pub const P: u16 = 0x19;
    pub const LEFT_BRACKET: u16 = 0x1A;
    pub const RIGHT_BRACKET: u16 = 0x1B;
    pub const ENTER: u16 = 0x1C;
    pub const LEFT_CTRL: u16 = 0x1D;
    pub const A: u16 = 0x1E;
    pub const S: u16 = 0x1F;
    pub const D: u16 = 0x20;
    pub const F: u16 = 0x21;
    pub const G: u16 = 0x22;
    pub const H: u16 = 0x23;
    pub const J: u16 = 0x24;
    pub const K: u16 = 0x25;
    pub const L: u16 = 0x26;
    pub const SEMICOLON: u16 = 0x27;
    pub const APOSTROPHE: u16 = 0x28;
    pub const GRAVE: u16 = 0x29;
    pub const LEFT_SHIFT: u16 = 0x2A;
    pub const BACKSLASH: u16 = 0x2B;
    pub const Z: u16 = 0x2C;
    pub const X: u16 = 0x2D;
    pub const C: u16 = 0x2E;
    pub const V: u16 = 0x2F;
    pub const B: u16 = 0x30;
    pub const N: u16 = 0x31;
    pub const M: u16 = 0x32;
    pub const COMMA: u16 = 0x33;
    pub const PERIOD: u16 = 0x34;
    pub const SLASH: u16 = 0x35;
    pub const RIGHT_SHIFT: u16 = 0x36;
    pub const NUMPAD_MULTIPLY: u16 = 0x37;
    pub const LEFT_ALT: u16 = 0x38;
    pub const SPACE: u16 = 0x39;
    pub const CAPS_LOCK: u16 = 0x3A;
    pub const F1: u16 = 0x3B;
    pub const F2: u16 = 0x3C;
    pub const F3: u16 = 0x3D;
    pub const F4: u16 = 0x3E;
    pub const F5: u16 = 0x3F;
    pub const F6: u16 = 0x40;
    pub const F7: u16 = 0x41;
    pub const F8: u16 = 0x42;
    pub const F9: u16 = 0x43;
    pub const F10: u16 = 0x44;
    pub const NUM_LOCK: u16 = 0x45;
    pub const SCROLL_LOCK: u16 = 0x46;
    pub const NUMPAD7: u16 = 0x47;
    pub const NUMPAD8: u16 = 0x48;
    pub const NUMPAD9: u16 = 0x49;
    pub const NUMPAD_MINUS: u16 = 0x4A;
    pub const NUMPAD4: u16 = 0x4B;
    pub const NUMPAD5: u16 = 0x4C;
    pub const NUMPAD6: u16 = 0x4D;
    pub const NUMPAD_PLUS: u16 = 0x4E;
    pub const NUMPAD1: u16 = 0x4F;
    pub const NUMPAD2: u16 = 0x50;
    pub const NUMPAD3: u16 = 0x51;
    pub const NUMPAD0: u16 = 0x52;
    pub const NUMPAD_PERIOD: u16 = 0x53;
    pub const F11: u16 = 0x57;
    pub const F12: u16 = 0x58;
    pub const LEFT_WIN: u16 = 0x5B;
}

/// The scan code for a key and whether it carries the `E0` prefix.
///
/// Extended keys share their base code with a numpad or modifier key and are
/// told apart by the prefix alone. `Pause` needs the `E1` sequence, which is not
/// a single stroke, so it has no code here.
pub fn of(key: Key) -> Option<(u16, bool)> {
    use code::*;
    Some(match key {
        Key::A => (A, false),
        Key::B => (B, false),
        Key::C => (C, false),
        Key::D => (D, false),
        Key::E => (E, false),
        Key::F => (F, false),
        Key::G => (G, false),
        Key::H => (H, false),
        Key::I => (I, false),
        Key::J => (J, false),
        Key::K => (K, false),
        Key::L => (L, false),
        Key::M => (M, false),
        Key::N => (N, false),
        Key::O => (O, false),
        Key::P => (P, false),
        Key::Q => (Q, false),
        Key::R => (R, false),
        Key::S => (S, false),
        Key::T => (T, false),
        Key::U => (U, false),
        Key::V => (V, false),
        Key::W => (W, false),
        Key::X => (X, false),
        Key::Y => (Y, false),
        Key::Z => (Z, false),
        Key::Num0 => (NUM0, false),
        Key::Num1 => (NUM1, false),
        Key::Num2 => (NUM2, false),
        Key::Num3 => (NUM3, false),
        Key::Num4 => (NUM4, false),
        Key::Num5 => (NUM5, false),
        Key::Num6 => (NUM6, false),
        Key::Num7 => (NUM7, false),
        Key::Num8 => (NUM8, false),
        Key::Num9 => (NUM9, false),
        Key::F1 => (F1, false),
        Key::F2 => (F2, false),
        Key::F3 => (F3, false),
        Key::F4 => (F4, false),
        Key::F5 => (F5, false),
        Key::F6 => (F6, false),
        Key::F7 => (F7, false),
        Key::F8 => (F8, false),
        Key::F9 => (F9, false),
        Key::F10 => (F10, false),
        Key::F11 => (F11, false),
        Key::F12 => (F12, false),
        Key::Escape => (ESC, false),
        Key::Backspace => (BACKSPACE, false),
        Key::Tab => (TAB, false),
        Key::Enter => (ENTER, false),
        Key::Space => (SPACE, false),
        Key::CapsLock => (CAPS_LOCK, false),
        Key::Minus => (MINUS, false),
        Key::Equal => (EQUALS, false),
        Key::BracketLeft => (LEFT_BRACKET, false),
        Key::BracketRight => (RIGHT_BRACKET, false),
        Key::Semicolon => (SEMICOLON, false),
        Key::Quote => (APOSTROPHE, false),
        Key::Backquote => (GRAVE, false),
        Key::Backslash => (BACKSLASH, false),
        Key::Comma => (COMMA, false),
        Key::Period => (PERIOD, false),
        Key::Slash => (SLASH, false),
        Key::ShiftLeft => (LEFT_SHIFT, false),
        Key::ShiftRight => (RIGHT_SHIFT, false),
        Key::ControlLeft => (LEFT_CTRL, false),
        Key::AltLeft => (LEFT_ALT, false),
        Key::ControlRight => (LEFT_CTRL, true),
        Key::AltRight => (LEFT_ALT, true),
        Key::Meta => (LEFT_WIN, true),
        Key::Insert => (NUMPAD0, true),
        Key::Delete => (NUMPAD_PERIOD, true),
        Key::Home => (NUMPAD7, true),
        Key::End => (NUMPAD1, true),
        Key::PageUp => (NUMPAD9, true),
        Key::PageDown => (NUMPAD3, true),
        Key::Up => (NUMPAD8, true),
        Key::Down => (NUMPAD2, true),
        Key::Left => (NUMPAD4, true),
        Key::Right => (NUMPAD6, true),
        Key::Numpad0 => (NUMPAD0, false),
        Key::Numpad1 => (NUMPAD1, false),
        Key::Numpad2 => (NUMPAD2, false),
        Key::Numpad3 => (NUMPAD3, false),
        Key::Numpad4 => (NUMPAD4, false),
        Key::Numpad5 => (NUMPAD5, false),
        Key::Numpad6 => (NUMPAD6, false),
        Key::Numpad7 => (NUMPAD7, false),
        Key::Numpad8 => (NUMPAD8, false),
        Key::Numpad9 => (NUMPAD9, false),
        Key::NumpadMultiply => (NUMPAD_MULTIPLY, false),
        Key::NumpadAdd => (NUMPAD_PLUS, false),
        Key::NumpadSubtract => (NUMPAD_MINUS, false),
        Key::NumpadDecimal => (NUMPAD_PERIOD, false),
        Key::NumpadEnter => (ENTER, true),
        Key::NumpadDivide => (SLASH, true),
        Key::Pause => return None,
        _ => return None,
    })
}
